### ISSUE TITLE
import tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl as rnn_cell ImportError: No module named core_rnn_cell_impl

### ISSUE THREAD

**Issue by alifirst** [snakeztc/NeuralDialog-CVAE#1]
Tensorflow 0.12.1

Traceback (most recent call last):
  File "kgcvae_swda.py", line 13, in <module>
    from models.cvae import KgRnnCVAE
  File "/home/ubuntu/NeuralDialog-CVAE/models/cvae.py", line 8, in <module>
    import tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl as rnn_cell
ImportError: No module named core_rnn_cell_impl

Which tensorflow version works fine with it?

**Comment by snakeztc** [comment]
I am able to run the code using tensorflow (0.12.1). I will do a pass on the code in the next few days to make it compatible with whichever latest version of Tensorflow. You could also change the import line to import the correct rnn_cell based on your local TF version.

**Comment by snakeztc** [comment]
@alifirst  The code is updated to tensorflow 1.3.0.
